### ISSUE TITLE
Why is the website still so broken?

### ISSUE THREAD

**Issue by stephenrs** [advaith1/wbotsite#13]
Hi, Widgetbot looks like a really interesting project and could be a great fit for the project I'm working on, but I'm terrified of it because the website is so unstable. I'm having a very hard time even being able to read through the documentation.

Yesterday, all of the links from the home page were returning 404 errors, and now today, it sometimes take more than a minute to load a page, and some of the pages load without any CSS styling.

I don't mean to complain, but is this project being enthusiastically maintained?

**Comment by Yomanz** [comment]
The documentation loads instantly for me and all of the staff and we see no CSS issues.
There were some documentation issues yesterday and they were solved (https://github.com/widgetbot-io/embed/issues/123)

I'm not sure what you're referring to but this project is maintained and we just released a big new update, so I would also call it enthusiatic..

**Comment by stephenrs** [comment]
This is how the iframe tutorial page loads for me right now...

"works for me" isn't that encouraging, if I'm being honest.

<img width="1928" alt="Screen Shot 2020-04-11 at 1 36 32 PM" src="https://user-images.githubusercontent.com/421262/79052103-a5fb3b80-7bf9-11ea-8d1c-3980740b5df6.png">

**Comment by stephenrs** [comment]
Should I report this as a new issue, since this one has been closed?

Also, we're all developers here, so I'd like to think we're on the same team. And, I'd imagine that you're not much different than I am: when a team can't manage to keep a documentation site running, it would make us all wonder about how solid the underlying project is. No?

And, when the developers respond to a problem report with a semi-hostile reaction like @Yomanz did, it speaks to the culture of the project, and it doesn't result in a very good onboarding experience.

I don't have anything against you, I'm just reporting what I've experienced as I've tried to adopt your technology.

**Comment by stephenrs** [comment]
Taking a quick closer look, it looks like a possible routing issue...

This URL works: https://docs.widgetbot.io/tutorial/iframes/

This one doesn't: https://docs.widgetbot.io/tutorial/tutorial/iframes/

Unfortunately, the second one represents the structure of the URLs presented on the site.

**Comment by Yomanz** [comment]
I'll look into the routing issues.
